<a href="https://colab.research.google.com/github/msrana172/Machine-Learning-ML-/blob/master/Naive_Bayes_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Naive Bayes Classifier by Mahaveer Singh **

1. Titanic Data Set Analysis

In [0]:
import pandas as pd
df = pd.read_excel('titanic3.xls')
df

pclass  survived  ...   body                        home.dest
0          1         1  ...    NaN                     St Louis, MO
1          1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2          1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3          1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4          1         0  ...    NaN  Montreal, PQ / Chesterville, ON
...      ...       ...  ...    ...                              ...
1304       3         0  ...  328.0                              NaN
1305       3         0  ...    NaN                              NaN
1306       3         0  ...  304.0                              NaN
1307       3         0  ...    NaN                              NaN
1308       3         0  ...    NaN                              NaN

[1309 rows x 14 columns]

In [0]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [0]:
df.drop(['name', 'sibsp', 'parch','ticket','cabin', 'embarked', 'boat', 'body', 'home.dest'], axis = 'columns',  inplace = True)

In [0]:
df.head()


pclass  survived     sex      age      fare
0       1         1  female  29.0000  211.3375
1       1         1    male   0.9167  151.5500
2       1         0  female   2.0000  151.5500
3       1         0    male  30.0000  151.5500
4       1         0  female  25.0000  151.5500

In [0]:
df.columns

Index(['pclass', 'survived', 'sex', 'age', 'fare'], dtype='object')

In [0]:
%matplotlib inline
target = df.survived
inputs = df.drop('survived',axis = 'columns')
inputs.head()

pclass     sex      age      fare
0       1  female  29.0000  211.3375
1       1    male   0.9167  151.5500
2       1  female   2.0000  151.5500
3       1    male  30.0000  151.5500
4       1  female  25.0000  151.5500

In [0]:
dumies = pd.get_dummies(inputs.sex)
dumies.head()

female  male
0       1     0
1       0     1
2       1     0
3       0     1
4       1     0

In [0]:
inputs = pd.concat([inputs, dumies], axis = 'columns')
inputs.head()

pclass     sex      age      fare  female  male
0       1  female  29.0000  211.3375       1     0
1       1    male   0.9167  151.5500       0     1
2       1  female   2.0000  151.5500       1     0
3       1    male  30.0000  151.5500       0     1
4       1  female  25.0000  151.5500       1     0

In [0]:
inputs.drop('sex',axis = 1, inplace = True)


In [0]:
inputs.head()

pclass      age      fare  female  male
0       1  29.0000  211.3375       1     0
1       1   0.9167  151.5500       0     1
2       1   2.0000  151.5500       1     0
3       1  30.0000  151.5500       0     1
4       1  25.0000  151.5500       1     0

In [0]:
inputs.columns[inputs.isna().any()]

Index(['age', 'fare'], dtype='object')

In [0]:
inputs.age = inputs.age.fillna(inputs.age.mean())
inputs.head()

pclass      age      fare  female  male
0       1  29.0000  211.3375       1     0
1       1   0.9167  151.5500       0     1
2       1   2.0000  151.5500       1     0
3       1  30.0000  151.5500       0     1
4       1  25.0000  151.5500       1     0

In [0]:
inputs.columns[inputs.isna().any()]

Index(['fare'], dtype='object')

In [0]:
inputs.fare = inputs.fare.fillna(inputs.fare.mean())
inputs.head()

pclass      age      fare  female  male
0       1  29.0000  211.3375       1     0
1       1   0.9167  151.5500       0     1
2       1   2.0000  151.5500       1     0
3       1  30.0000  151.5500       0     1
4       1  25.0000  151.5500       1     0

In [0]:
inputs.columns[inputs.isna().any()]

Index([], dtype='object')

In [0]:
inputs.shape

(1309, 5)

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(inputs, target, test_size = 0.2)

In [0]:
len(X_train)

1047

In [0]:
len(X_test)

262

In [0]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [0]:
model.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
model.score(X_test, y_test)

0.7595419847328244

In [0]:
X_test[:10]

pclass        age      fare  female  male
623       3   6.000000   31.2750       1     0
642       3  13.000000   31.3875       0     1
309       1  31.000000  164.8667       1     0
711       3  28.000000    7.2500       0     1
917       3  39.000000   13.4167       0     1
417       2  26.000000   10.5000       0     1
394       2  18.000000   73.5000       0     1
573       2  27.000000   10.5000       1     0
59        1  29.881135   27.7208       1     0
887       3  29.881135    8.1125       0     1

In [0]:
y_test[:10]

623    0
642    0
309    1
711    0
917    1
417    0
394    0
573    1
59     1
887    1
Name: survived, dtype: int64

In [0]:
model.predict(X_test[:10])

array([1, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [0]:
model.predict_proba(X_test[:10])

array([[3.67523952e-02, 9.63247605e-01],
       [9.82697909e-01, 1.73020913e-02],
       [1.29718851e-05, 9.99987028e-01],
       [9.88993531e-01, 1.10064693e-02],
       [9.89654576e-01, 1.03454236e-02],
       [9.77410333e-01, 2.25896668e-02],
       [9.25139606e-01, 7.48603944e-02],
       [3.85244250e-02, 9.61475575e-01],
       [1.24039617e-02, 9.87596038e-01],
       [9.89270159e-01, 1.07298409e-02]])

2. Spam Classification

In [0]:
import pandas as pd
data = pd.read_csv('spam1.csv')
data.head()

v1  ... Unnamed: 4
0   ham  ...        NaN
1   ham  ...        NaN
2  spam  ...        NaN
3   ham  ...        NaN
4   ham  ...        NaN

[5 rows x 5 columns]

In [0]:
data.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'], axis = 'columns',  inplace = True)
data.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [0]:
new_data = data.rename(columns = {"v1": "Category", "v2": "Message"}) 

In [0]:
new_data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [0]:
new_data.describe()

Category                 Message
count      5572                    5572
unique        2                    5163
top         ham  Sorry, I'll call later
freq       4825                      30

In [0]:
new_data.groupby('Category').describe()

spam                                   
           count mean  std  min  25%  50%  75%  max
Category                                           
ham       4825.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
spam       747.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

In [0]:
new_data['spam'] = new_data['Category'].apply(lambda x : 1 if x == 'spam' else 0 )


In [0]:
new_data.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(new_data.Message, new_data.spam, test_size = 0.25)

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
X_train_count = vec.fit_transform(X_train.values)
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [0]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
emails = [
          'I cant pick the phone right now. Pls send a message',
          "I don't want you to leave. But i'm barely doing what i can to stay sane. fighting with you constantly isn't helping.",
          "The current leading bid is 151. To pause this auction send OUT. Customer Care: 08718726270",
          "Free entry to the gr8prizes wkly comp 4 a chance to win the latest Nokia 8800, PSP or �250 cash every wk.TXT GREAT to 80878 http//www.gr8prizes.com 08715705022"
         ]

In [0]:
email_count = vec.transform(emails)
model.predict(email_count)

array([0, 0, 1, 1])

In [0]:
X_test_count = vec.transform(X_test)
model.score(X_test_count, y_test)

0.9849246231155779

In [0]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
                ('vectorize', CountVectorizer()),
                ('nb', MultinomialNB())
])

In [0]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('vectorize',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [0]:
clf.score(X_test, y_test)

0.9849246231155779

In [0]:
clf.predict(emails)

array([0, 0, 1, 1])